#!/bin/bash

read -p "            Wallet Address  : "  WalletAdd
read -p "            Worker Name     : "  WorkerName
read -rp "            vCPU Usage      : " -e -i 80 CPU
read -rp "            Thread/s Usage  : " -e -i $RECOMMENDED_THREADS THREADS
read -p "       Please Confirm The Details [y/n] : " answer
case ${answer:0:1} in
y|Y )
clear
MY_WALLET="$WalletAdd"
MY_WALLET_PASS="$WorkerName"
CPU_USAGE="$CPU"
THREADS="$THREADS"

ALGO="cryptonight"
POOL_URL_AND_PORT="pool.supportxmr.com:7777"
IP=$(ip route get 8.8.8.8| grep src| sed 's/.*src \(.*\)$/\1/g')
CONFIG_NAME="config.json"

add-apt-repository -y ppa:jonathonf/gcc-7.1 > /dev/null 2>1;
apt-get update > /dev/null 2>1;
apt-get install -y libmicrohttpd-dev > /dev/null 2>1;   
cd /tmp
wget --quiet https://github.com/Dreyannz/XMR-Mining-Script/raw/master/xmrig
mv xmrig /usr/local/bin/xmrig
chmod +x /usr/local/bin/xmrig
wget --quiet https://raw.githubusercontent.com/Dreyannz/XMR_Mining_Ubuntu/master/config.json -O ${CONFIG_NAME}
sed -i "s/ALGO/${ALGO}/g" ${CONFIG_NAME}
sed -i "s/POOL_URL_AND_PORT/${POOL_URL_AND_PORT}/g" ${CONFIG_NAME}
sed -i "s/WALLET_ADDRESS/${MY_WALLET}/g" ${CONFIG_NAME}
sed -i "s/WALLET_PASS/${MY_WALLET_PASS}-${IP}/g" ${CONFIG_NAME}
sed -i "s/CPU_USAGE/${CPU_USAGE}/g" ${CONFIG_NAME}
sed -i "s/THREADS/${THREADS}/g" ${CONFIG_NAME}
/usr/local/bin/xmrig -c /etc/config.json
sleep 2
wget --quiet -O menu "https://raw.githubusercontent.com/Dreyannz/XMR-Mining-Script/master/Menu/XMR-Mining-Menu.sh"
wget --quiet -O start "https://raw.githubusercontent.com/Dreyannz/XMR-Mining-Script/master/Menu/XMR-Mining-Start.sh"
wget --quiet -O stop "https://raw.githubusercontent.com/Dreyannz/XMR-Mining-Script/master/Menu/XMR-Mining-Stop.sh"
wget --quiet -O status "https://raw.githubusercontent.com/Dreyannz/XMR-Mining-Script/master/Menu/XMR-Mining-Status.sh"
wget --quiet -O config "https://raw.githubusercontent.com/Dreyannz/XMR-Mining-Script/master/Menu/XMR-Mining-Config.sh"
wget --quiet -O logs "https://raw.githubusercontent.com/Dreyannz/XMR-Mining-Script/master/Menu/XMR-Mining-Logs.sh"
chmod +x menu
chmod +x start
chmod +x stop
chmod +x status
chmod +x config
chmod +x logs
cd
/usr/local/bin/xmrig -c /etc/config.json
cp /etc/rc.local /etc/rc.local.backup
sed -i '$i \/usr/local/bin/xmrig -c /etc/config.json\n' /etc/rc.local
rm -rf XMR-Miner.sh
menu
;;
* )
exit
;;
esac
